{% set version = "3.26.0" %}

package:
  name: tox
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tox/tox-{{ version }}.tar.gz
  sha256: 44f3c347c68c2c68799d7d44f1808f9d396fc8a1a500cbc624253375c7ae107e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - tox = tox:cmdline
    - tox-quickstart = tox._quickstart:main

requirements:
  host:
    - python >=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*
    - pip
    - setuptools-scm
  run:
    - python >=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*
    - colorama >=0.4.1
    - filelock >=3.0.0
    - importlib-metadata >=0.12
    - packaging >=14
    - pluggy >=0.12.0
    - py >=1.4.17
    - six >=1.14.0
    - tomli >=2.0.1
    - virtualenv !=20.0.0,!=20.0.1,!=20.0.2,!=20.0.3,!=20.0.4,!=20.0.5,!=20.0.6,!=20.0.7,>=16.0.0

{% set skip_tests = [
  "get_info_uses_hook_path",
  "some_files_exist",
  "parallel_inception",
  "provision_interrupt_child",
  "parallel_interrupt",
  "provision_non_canonical_dep",
] | join(" or ") %}

test:
  source_files:
    - tests
  requires:
    - flaky >=3.4.0
    - freezegun >=0.3.11
    - pip
    - psutil >=5.6.1
    - pytest >=4.0.0
    - pytest-cov >=2.5.1
    - pytest-mock >=1.10.0
    - pytest-randomly >=1.0.0
  imports:
    - tox
  commands:
    - pip check
    - tox --version
    - tox --help
    - tox-quickstart --version
    - pytest -vv --cov=tox --no-cov-on-fail --cov-report=term-missing:skip-covered -k "not ({{ skip_tests }})" --cov-fail-under=88

about:
  home: https://tox.wiki
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: virtualenv-based automation of test activities
  description: |
    Tox is a generic virtualenv management and test command line tool you can use for
    - checking your package installs correctly with different Python versions and interpreters
    - running your tests in each of the environments, configuring your test tool of choice
    - acting as a frontend to Continuous Integration servers, greatly reducing boilerplate
      and merging CI and shell-based testing.
  doc_url: https://tox.readthedocs.org
  dev_url: https://github.com/tox-dev/tox
  doc_source_url: https://github.com/tox-dev/tox/tree/{{ version }}/docs

extra:
  recipe-maintainers:
    - cshaley
    - kalefranz
    - sannykr
    - bollwyvl
