{% set name = "tox" %}
{% set version = "4.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tox-{{ version }}.tar.gz
  sha256: 9e2c5091a117d03b583c57c4c40aecd068099c17d40520e7b165e85c19334534

build:
  noarch: python
  entry_points:
    - tox = tox.run:run
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - hatch-vcs >=0.3
    - hatchling >=1.17.1
    - pip
  run:
    - python >=3.7
    - cachetools >=5.3.1
    - chardet >=5.1
    - colorama >=0.4.6
    - filelock >=3.12.2
    - importlib-metadata >=6.6
    - packaging >=23.1
    - platformdirs >=3.5.3
    - pluggy >=1
    - pyproject-api >=1.5.2
    - tomli >=2.0.1
    - typing-extensions >=4.6.3
    - virtualenv >=20.23


{% set skip_tests = [
  "build_wheel_in_non_base_pkg_env",
  "deps_remove_recreate",
  "env_log",
  "find_alias_on_path",
  "get_info_uses_hook_path",
  "install_command_no_packages",
  "install_pkg_via",
  "keyboard_interrupt",
  "legacy_cli_flags",
  "local_subprocess",
  "override_incorrect",
  "package_only",
  "parallel_inception",
  "parallel_interrupt",
  "pip_install_constraint_file_create_change",
  "pip_install_constraint_file_new",
  "pip_install_path",
  "pip_install_req_file_req_like",
  "pip_install_requirements_file_deps",
  "pip_pre",
  "pip_req_path",
  "pkg_dep_remove_recreate",
  "pkg_env_dep_remove_recreate",
  "plugin_hooks_and_order",
  "provision_interrupt_child",
  "provision_non_canonical_dep",
  "pyproject_deps_from_static",
  "pyproject_deps_static_with_dynamic",
  "pyproject_no_build_editable_fallback",
  "python_disable_hash_seed",
  "python_generate_hash_seed",
  "python_keep_hash_seed",
  "python_set_hash_seed",
  "requirements_txt",
  "skip_develop_mode",
  "some_files_exist",
  "test_constrain_package_deps",
  "test_package_pyproject",
  "tox_install_pkg_sdist",
  "tox_install_pkg_wheel",
  "verbosity_guess_miss_match",
] | join(" or ") %}

test:
  source_files:
    - tests
  requires:
    - python-build >=0.9
    - covdefaults >=2.2.2
    - devpi-process >=0.3
    - diff-cover >=7.3
    - distlib >=0.3.6
    - flaky >=3.7
    - hatch-vcs >=0.3
    - hatchling >=1.12.2
    - psutil >=5.9.4
    - pytest >=7.2
    - pytest-cov >=4
    - pytest-mock >=3.10
    - pytest-xdist >=3.1
    - re-assert >=1.1
    - wheel >=0.38.4
    - time-machine >=2.9.0
  imports:
    - tox
  commands:
    - pip check
    - tox --version
    - tox --help
    - pytest -vv --cov=tox --no-cov-on-fail --cov-report=term-missing:skip-covered -k "not ({{ skip_tests }})" --cov-fail-under=94

about:
  home: https://tox.wiki
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: virtualenv-based automation of test activities
  description: |
    Tox is a generic virtualenv management and test command line tool you can use for
    - checking your package installs correctly with different Python versions and interpreters
    - running your tests in each of the environments, configuring your test tool of choice
    - acting as a frontend to Continuous Integration servers, greatly reducing boilerplate
      and merging CI and shell-based testing.
  doc_url: https://tox.readthedocs.org
  dev_url: https://github.com/tox-dev/tox
  doc_source_url: https://github.com/tox-dev/tox/tree/{{ version }}/docs

extra:
  recipe-maintainers:
    - rxm7706
    - cshaley
    - kalefranz
    - sannykr
    - bollwyvl
