{% set version = "3.6.0" %}

package:
  name: tox
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tox/tox-{{ version }}.tar.gz
  sha256: 304177defdcb403d84aeb0400b1625b1e65a7fff19f0441329f9f76ebf67882f


build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - tox = tox:cmdline
    - tox-quickstart = tox._quickstart:main

requirements:
  build:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - py >=1.4.17, <2
    - pluggy >=0.3.0,<1.0
    - virtualenv >=1.11.2
    - setuptools >=30.0.0
    - six >=1.0.0,<2
    - toml >=0.9.4
    - filelock >=3.0.0,<4

test:
  imports:
    - tox
  commands:
    - tox --version
    - tox-quickstart --version

about:
  home: https://github.com/tox-dev/tox
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'virtualenv-based automation of test activities'
  description: |
    Tox is a generic virtualenv management and test command line tool you can use for
    - checking your package installs correctly with different Python versions and interpreters
    - running your tests in each of the environments, configuring your test tool of choice
    - acting as a frontend to Continuous Integration servers, greatly reducing boilerplate
      and merging CI and shell-based testing.
  doc_url: https://tox.readthedocs.org
  dev_url: https://github.com/tox-dev/tox

extra:
  recipe-maintainers:
    - cshaley
    - kalefranz
    - sannykr
